version: "3.9"

services:
  aggregator:
    build: .
    container_name: csv_aggregator

    volumes:
      - .:/app

    working_dir: /app

    command: >
      python aggregator.py
      --input ad_data.csv
      --output results

  test:
    build: .
    container_name: csv_aggregator_test

    volumes:
      - .:/app

    working_dir: /app

    command: pytest -v